/*
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RghUiModule extends AbstractRghUiModule {

	public RghUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
