/**
 * generated by Xtext 2.32.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Context#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getContext()
 * @model
 * @generated
 */
public interface Context extends Steps
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Feature}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference list.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getContext_Feature()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeature();

} // Context
