/**
 * generated by Xtext 2.32.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Feature#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Description)
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getFeature_Name()
   * @model containment="true"
   * @generated
   */
  Description getName();

  /**
   * Sets the value of the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Feature#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Description value);

} // Feature
