/**
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getModule()
 * @model
 * @generated
 */
public interface Module extends Context
{
} // Module
