/**
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghFactory
 * @model kind="package"
 * @generated
 */
public interface RghPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rgh";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mcmaster/requirements/gherkin/rgh/Rgh";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rgh";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RghPackage eINSTANCE = org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModelImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Requirement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REQUIREMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.StepsImpl <em>Steps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.StepsImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getSteps()
   * @generated
   */
  int STEPS = 1;

  /**
   * The number of structural features of the '<em>Steps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ContextImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NAME = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModuleImpl <em>Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModuleImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getModule()
   * @generated
   */
  int MODULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__NAME = CONTEXT__NAME;

  /**
   * The number of structural features of the '<em>Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_FEATURE_COUNT = CONTEXT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.OperationImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = CONTEXT__NAME;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = CONTEXT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.GivenImpl <em>Given</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.GivenImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getGiven()
   * @generated
   */
  int GIVEN = 5;

  /**
   * The feature id for the '<em><b>Preconditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN__PRECONDITIONS = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Given</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.WhenImpl <em>When</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.WhenImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getWhen()
   * @generated
   */
  int WHEN = 6;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__EVENTS = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>When</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ThenImpl <em>Then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ThenImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getThen()
   * @generated
   */
  int THEN = 7;

  /**
   * The feature id for the '<em><b>Postconditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN__POSTCONDITIONS = STEPS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_FEATURE_COUNT = STEPS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PreconditionImpl <em>Precondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PreconditionImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getPrecondition()
   * @generated
   */
  int PRECONDITION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Precondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRECONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.EventImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PostconditionImpl <em>Postcondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PostconditionImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getPostcondition()
   * @generated
   */
  int POSTCONDITION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Postcondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSTCONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.DescriptionImpl
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Model#getRequirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Requirement</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Model#getRequirement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Requirement();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Steps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Steps
   * @generated
   */
  EClass getSteps();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Context#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Context#getName()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Module <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Module
   * @generated
   */
  EClass getModule();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Given <em>Given</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Given</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Given
   * @generated
   */
  EClass getGiven();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Given#getPreconditions <em>Preconditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Preconditions</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Given#getPreconditions()
   * @see #getGiven()
   * @generated
   */
  EReference getGiven_Preconditions();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.When <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.When
   * @generated
   */
  EClass getWhen();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.When#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.When#getEvents()
   * @see #getWhen()
   * @generated
   */
  EReference getWhen_Events();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Then <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Then</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Then
   * @generated
   */
  EClass getThen();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Then#getPostconditions <em>Postconditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Postconditions</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Then#getPostconditions()
   * @see #getThen()
   * @generated
   */
  EReference getThen_Postconditions();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition <em>Precondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Precondition</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition
   * @generated
   */
  EClass getPrecondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition#getName()
   * @see #getPrecondition()
   * @generated
   */
  EAttribute getPrecondition_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Precondition#getDescription()
   * @see #getPrecondition()
   * @generated
   */
  EReference getPrecondition_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Event#getDescription()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition <em>Postcondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Postcondition</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition
   * @generated
   */
  EClass getPostcondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition#getName()
   * @see #getPostcondition()
   * @generated
   */
  EAttribute getPostcondition_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Postcondition#getDescription()
   * @see #getPostcondition()
   * @generated
   */
  EReference getPostcondition_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Description#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Description#getValue()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RghFactory getRghFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModelImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Requirement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REQUIREMENT = eINSTANCE.getModel_Requirement();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.StepsImpl <em>Steps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.StepsImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getSteps()
     * @generated
     */
    EClass STEPS = eINSTANCE.getSteps();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ContextImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NAME = eINSTANCE.getContext_Name();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModuleImpl <em>Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ModuleImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getModule()
     * @generated
     */
    EClass MODULE = eINSTANCE.getModule();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.OperationImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.GivenImpl <em>Given</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.GivenImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getGiven()
     * @generated
     */
    EClass GIVEN = eINSTANCE.getGiven();

    /**
     * The meta object literal for the '<em><b>Preconditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GIVEN__PRECONDITIONS = eINSTANCE.getGiven_Preconditions();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.WhenImpl <em>When</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.WhenImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getWhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getWhen();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHEN__EVENTS = eINSTANCE.getWhen_Events();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ThenImpl <em>Then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.ThenImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getThen()
     * @generated
     */
    EClass THEN = eINSTANCE.getThen();

    /**
     * The meta object literal for the '<em><b>Postconditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference THEN__POSTCONDITIONS = eINSTANCE.getThen_Postconditions();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PreconditionImpl <em>Precondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PreconditionImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getPrecondition()
     * @generated
     */
    EClass PRECONDITION = eINSTANCE.getPrecondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRECONDITION__NAME = eINSTANCE.getPrecondition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRECONDITION__DESCRIPTION = eINSTANCE.getPrecondition_Description();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.EventImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__DESCRIPTION = eINSTANCE.getEvent_Description();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PostconditionImpl <em>Postcondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.PostconditionImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getPostcondition()
     * @generated
     */
    EClass POSTCONDITION = eINSTANCE.getPostcondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSTCONDITION__NAME = eINSTANCE.getPostcondition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POSTCONDITION__DESCRIPTION = eINSTANCE.getPostcondition_Description();

    /**
     * The meta object literal for the '{@link org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.DescriptionImpl
     * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl.RghPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__VALUE = eINSTANCE.getDescription_Value();

  }

} //RghPackage
