/**
 * generated by Xtext 2.32.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Steps</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage#getSteps()
 * @model
 * @generated
 */
public interface Steps extends EObject
{
} // Steps
