/*
 * generated by Xtext 2.32.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mcmaster.requirements.gherkin.rgh.ui.internal.RghActivator;

public class RghUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RghActivator.getInstance().getInjector("org.xtext.mcmaster.requirements.gherkin.rgh.Rgh");
	}

}
