/*
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mcmaster.requirements.gherkin.rgh.RghRuntimeModule;
import org.xtext.mcmaster.requirements.gherkin.rgh.RghStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RghIdeSetup extends RghStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RghRuntimeModule(), new RghIdeModule()));
	}
	
}
