/*
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.ide;


/**
 * Use this class to register ide components.
 */
public class RghIdeModule extends AbstractRghIdeModule {
}
