/*
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.mcmaster.requirements.gherkin.rgh.services.RghGrammarAccess;

@SuppressWarnings("all")
public class RghSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RghGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Given_Then_When___GivenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___ThenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___WhenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RghGrammarAccess) access;
		match_Given_Then_When___GivenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___ThenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___WhenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getGivenAccess().getGivenKeyword_0()), new TokenAlias(false, false, grammarAccess.getGivenAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getGivenAccess().getRightCurlyBracketKeyword_3())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getThenAccess().getThenKeyword_0()), new TokenAlias(false, false, grammarAccess.getThenAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getThenAccess().getRightCurlyBracketKeyword_3())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getWhenAccess().getWhenKeyword_0()), new TokenAlias(false, false, grammarAccess.getWhenAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getWhenAccess().getRightCurlyBracketKeyword_3())));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Given_Then_When___GivenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___ThenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___WhenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__.equals(syntax))
				emit_Given_Then_When___GivenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___ThenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___WhenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('Given' '{' '}') | ('When' '{' '}') | ('Then' '{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_Given_Then_When___GivenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___ThenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3___or___WhenKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
