<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pfcsm" nsURI="http://www.example.org/pfcsm" nsPrefix="pfcsm">
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTo" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceFrom" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class_Diagram_Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClass" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/referenceTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/referenceFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcMult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1..1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tgtMult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1..1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ascSrc" lowerBound="1"
        eType="#//Element" eOpposite="#//Element/associationTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ascTgt" lowerBound="1"
        eType="#//Element" eOpposite="#//Element/associationFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tgtMult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1..1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance" eSuperTypes="#//Reference"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOR" eSuperTypes="#//Reference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteClass" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="String"/>
    <eLiterals name="Int" value="1"/>
    <eLiterals name="Double" value="2"/>
    <eLiterals name="Boolean" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataStructure">
    <eLiterals name="Value"/>
    <eLiterals name="Array" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationTo" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/ascSrc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationFrom" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/ascTgt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uses" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Produces" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Element"/>
</ecore:EPackage>
