<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tmat" nsURI="http://www.example.org/tmat" nsPrefix="tmat">
  <eClassifiers xsi:type="ecore:EClass" name="Traceability_Matrix">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectrequirements" upperBound="-1"
        eType="#//ProjectRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="design" upperBound="-1"
        eType="#//Design" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" upperBound="-1"
        eType="#//Implementation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testing" upperBound="-1"
        eType="#//Testing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="review" upperBound="-1"
        eType="#//Review" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Design" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implementation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Testing" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Review" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ID" eSuperTypes="#//ProjectRequirements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectRequirements" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//ProjectRequirements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Approval" eSuperTypes="#//Review"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comments" eSuperTypes="#//Review"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" eSuperTypes="#//ProjectRequirements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Design"/>
  <eClassifiers xsi:type="ecore:EClass" name="SatisfiabilityCheck" eSuperTypes="#//Design"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//Review"/>
  <eClassifiers xsi:type="ecore:EClass" name="Status" eSuperTypes="#//Implementation"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTest" eSuperTypes="#//Testing"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemTest" eSuperTypes="#//Testing"/>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceTest" eSuperTypes="#//Testing"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserAcceptanceTest" eSuperTypes="#//Testing"/>
</ecore:EPackage>
