/**
 * generated by Xtext 2.30.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.rgh.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mcmaster.requirements.gherkin.rgh.rgh.Operation;
import org.xtext.mcmaster.requirements.gherkin.rgh.rgh.RghPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationImpl extends ContextImpl implements Operation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RghPackage.Literals.OPERATION;
  }

} //OperationImpl
