<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rmdl" nsURI="http://www.example.org/rmdl" nsPrefix="rmdl">
  <eClassifiers xsi:type="ecore:EClass" name="Requirements" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verifyMethod" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//Decomposition" eOpposite="#//Decomposition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Decomposition"
        eOpposite="#//Decomposition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationTgt" eType="#//Verification"
        eOpposite="#//Verification/requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfiedBy" eType="#//Trace"
        eOpposite="#//Trace/requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_root" lowerBound="1"
        eType="#//Requirement_Root" eOpposite="#//Requirement_Root/requirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functional" eSuperTypes="#//Requirements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Qualitative" eSuperTypes="#//Requirements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//Requirements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Requirement_Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_root" lowerBound="1"
        eType="#//Requirement_Root" eOpposite="#//Requirement_Root/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement_Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
        eType="#//Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testcase" upperBound="-1"
        eType="#//TestCase" containment="true" eOpposite="#//TestCase/requirement_root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" upperBound="-1"
        eType="#//Package" containment="true" eOpposite="#//Package/requirement_root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designelement" upperBound="-1"
        eType="#//DesignElement" containment="true" eOpposite="#//DesignElement/requirement_root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirements" containment="true" eOpposite="#//Requirements/requirement_root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Safety" eSuperTypes="#//Requirements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="designelement" lowerBound="1"
        eType="#//DesignElement" eOpposite="#//DesignElement/satisfies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirements" eOpposite="#//Requirements/satisfiedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfies" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/designelement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_root" lowerBound="1"
        eType="#//Requirement_Root" eOpposite="#//Requirement_Root/designelement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="children" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationSrc" upperBound="-1"
        eType="#//Verification" eOpposite="#//Verification/testcase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TestType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_root" lowerBound="1"
        eType="#//Requirement_Root" eOpposite="#//Requirement_Root/testcase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Verification" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testcase" lowerBound="1"
        eType="#//TestCase" eOpposite="#//TestCase/verificationSrc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirements" eOpposite="#//Requirements/verificationTgt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Requirements" eOpposite="#//Requirements/child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Requirements" eOpposite="#//Requirements/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestType">
    <eLiterals name="UnitTest"/>
    <eLiterals name="ClassTest" value="1"/>
    <eLiterals name="WhiteBox" value="2"/>
    <eLiterals name="BlackBox" value="3"/>
  </eClassifiers>
</ecore:EPackage>
