<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rmdl" nsURI="http://www.example.org/rmdl" nsPrefix="rmdl">
  <eClassifiers xsi:type="ecore:EClass" name="Requirements" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="review" lowerBound="1"
        upperBound="-1" eType="#//Review" eOpposite="#//Review/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testcase" lowerBound="1"
        upperBound="-1" eType="#//TestCase" eOpposite="#//TestCase/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceTo" upperBound="-1"
        eType="#//DesignElement" eOpposite="#//DesignElement/traceFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functional" eSuperTypes="#//RequirementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Qualitative" eSuperTypes="#//RequirementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//RequirementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement_Canvas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" upperBound="-1"
        eType="#//TestCase" containment="true" eOpposite="#//TestCase/requirement_canvas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//RequirementType" containment="true" eOpposite="#//RequirementType/requirement_canvas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="review" upperBound="-1"
        eType="#//Review" containment="true" eOpposite="#//Review/requirement_canvas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designElement" upperBound="-1"
        eType="#//DesignElement" containment="true" eOpposite="#//DesignElement/requirement_canvas"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementcontainer" upperBound="-1"
        eType="#//RequirementContainer" containment="true" eOpposite="#//RequirementContainer/requirement_canvas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rmdl_project" eType="#//RMDL_Project"
        eOpposite="#//RMDL_Project/requirement_canvas"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Safety" eSuperTypes="#//RequirementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DesignElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHardware" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSoftware" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" eType="#//Requirement_Canvas"
        eOpposite="#//Requirement_Canvas/designElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementationOf" eType="#//Feature_Model_Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceFrom" upperBound="-1"
        eType="#//Requirements" eOpposite="#//Requirements/traceTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TestType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" lowerBound="1"
        eType="#//Requirement_Canvas" eOpposite="#//Requirement_Canvas/testCase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasPassed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" lowerBound="1"
        upperBound="-1" eType="#//Requirements" eOpposite="#//Requirements/testcase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestType">
    <eLiterals name="UnitTest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reviewer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" lowerBound="1"
        eType="#//Requirement_Canvas" eOpposite="#//Requirement_Canvas/review"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isApproved" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" lowerBound="1"
        upperBound="-1" eType="#//Requirements" eOpposite="#//Requirements/review"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature_Model_Element" eSuperTypes="#//Feature_Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature_Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rmdl_project" eType="#//RMDL_Project"
        eOpposite="#//RMDL_Project/feature_model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product_variant" upperBound="-1"
        eType="#//Product_Variant" containment="true" eOpposite="#//Product_Variant/feature_model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature_model_root" eType="#//Feature_Model_Root"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature_model_element"
        upperBound="-1" eType="#//Feature_Model_Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMDL_Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature_model" upperBound="-1"
        eType="#//Feature_Model" containment="true" eOpposite="#//Feature_Model/rmdl_project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" upperBound="-1"
        eType="#//Requirement_Canvas" containment="true" eOpposite="#//Requirement_Canvas/rmdl_project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature_Entity" abstract="true" eSuperTypes="#//Requirement_Canvas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composes" eType="#//Feature_Entity"
        eOpposite="#//Feature_Entity/mandatory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatory" upperBound="-1"
        eType="#//Feature_Entity" eOpposite="#//Feature_Entity/composes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionOf" eType="#//Feature_Entity"
        eOpposite="#//Feature_Entity/optional"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optional" upperBound="-1"
        eType="#//Feature_Entity" eOpposite="#//Feature_Entity/optionOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" upperBound="-1"
        eType="#//Feature_Entity" eOpposite="#//Feature_Entity/alternativeOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOf" eType="#//Feature_Entity"
        eOpposite="#//Feature_Entity/alternative"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature_Model_Root" eSuperTypes="#//Feature_Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementContainer" eSuperTypes="#//Requirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirements" lowerBound="2"
        upperBound="-1" eType="#//RequirementType" containment="true" eOpposite="#//RequirementType/requirementContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" eType="#//Requirement_Canvas"
        eOpposite="#//Requirement_Canvas/requirementcontainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementType" abstract="true" eSuperTypes="#//Requirements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementContainer" eType="#//RequirementContainer"
        eOpposite="#//RequirementContainer/ownedRequirements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacedBy" eType="#//RequirementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingReq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement_canvas" eType="#//Requirement_Canvas"
        eOpposite="#//Requirement_Canvas/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementOrigin" eType="#//RequirementType"
        eOpposite="#//RequirementType/requirementVariant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementVariant" upperBound="-1"
        eType="#//RequirementType" eOpposite="#//RequirementType/requirementOrigin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product_Variant" eSuperTypes="#//Feature_Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature_model" lowerBound="1"
        eType="#//Feature_Model" eOpposite="#//Feature_Model/product_variant"/>
  </eClassifiers>
</ecore:EPackage>
