/*
 * generated by Xtext 2.32.0
 */
package org.xtext.mcmaster.requirements.gherkin.rgh.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.mcmaster.requirements.gherkin.rgh.ui.internal.RghActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RghExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RghActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RghActivator activator = RghActivator.getInstance();
		return activator != null ? activator.getInjector(RghActivator.ORG_XTEXT_MCMASTER_REQUIREMENTS_GHERKIN_RGH_RGH) : null;
	}

}
